### ISSUE TITLE
Make user not required to sign in when viewing questions

### ISSUE THREAD

**Issue by leindfraust** [jerommiole/pinoy-overflow#50]
Hello, first of all, great work you have with Pinoy Overflow, I am really liking the project so far and been visiting it lately to see some progress. 

I just have noticed that you are required to sign in when viewing questions. Which is kind of a problem. In StackOverflow, they do not require you to sign in to view questions. It is also detrimental to SEO if users are required to sign in to continue viewing a question. Instead, only ask for sign-in when users want to comment or upvote.

God bless!

**Comment by jerommiole** [comment]
Hello Romel! Thanks for visiting 😁
I'll add this to my task. 

Have a nice day! Happy coding 😀
