### ISSUE TITLE
add contributing docs for steps for contribution

### ISSUE THREAD

**Issue by AIA-UnKNOWN** [jerommiole/pinoy-overflow#64]

**Comment by jerommiole** [comment]
You're right! :) 
On it. Thank you!

**Comment by jerommiole** [comment]
Hi @AIA-UnKNOWN , you can check the updated [README.md](https://github.com/jerommiole/pinoy-overflow#readme) now. Happy coding! :)

**Comment by AIA-UnKNOWN** [comment]
@jerommiole this is great
