### ISSUE TITLE
documentation for setting up both frontend and backend

### ISSUE THREAD

**Issue by AIA-UnKNOWN** [jerommiole/pinoy-overflow#66]

**Comment by AIA-UnKNOWN** [comment]
@jerommiole what are the steps for setting up its backend, I've already managed to make the frontend work but not on the backend side

**Comment by jerommiole** [comment]
Hi Aj! I hope you're doing good. 
Can you go to this? https://discord.com/channels/1177120877620498592/1177124691148808233 
Let's have a chat there :)

**Comment by AIA-UnKNOWN** [comment]
Hi Jerom,

Can you add me through my username *ajboyianabordo,*
*I can't seem to find the channel.*

**Comment by jerommiole** [comment]
Hi @AIA-UnKNOWN , try here https://discord.gg/66bTbzmu

**Comment by jerommiole** [comment]
[env.setupApiKeys.txt](https://github.com/jerommiole/pinoy-overflow/files/13463109/env.setupApiKeys.txt)

please see the attach file.
